### ISSUE TITLE
Append isNewEntry to entry

### ISSUE THREAD

**Issue by chrisrowe** [therefinerynz/courier#1]
The `onSaveEntry` event provides a `isNewEntry` attribute so you know whether this is a new entry or a an update to an existing one. It'd be great to have this avalible in the Bluepring Event Trigger Conditions so notifications aren't sent if entries are updated in the backend for any reason.

**Comment by chrisrowe** [comment]
On further digging I can see `isNewEntry` does indeed get set but it's outside the `{{ entry }}` model.

`{% if entry.section == "2" and isNewEntry %}true{% endif %}`

Thanks!

**Comment by elvdm** [comment]
Yep, the `entry` variable is separate from `isNewEntry` as they are separate params on the fired `onSaveEntry` event.

All of a fired event's params are made available in a Blueprint's fields. You can check which params are available by referencing the documentation for the event. Documentation exists [here](https://craftcms.com/docs/plugins/events-reference) for native Craft events.

Perhaps this should be better documented in the readme, @anthonyjc

**Comment by anthonyjc** [comment]
Good idea, I've updated the readme accordingly to provide some clarification.  Thanks @elvdm
