### ISSUE TITLE
Accessing entry variables in email template

### ISSUE THREAD

**Issue by siebird** [therefinerynz/courier#2]
Awesome, well thought out plugin. Thanks for sharing!

As the title states, is it possible to access the entry's custom fields in the email template? I tried `entry.customField` and I got this error:

```
Could not create email for the blueprint named “WS1: Status Update”.
Template parse error encountered while parsing the HTML Email Template file located at path “emails/_workshop-status” for the blueprint named “WS1: Status Update”:
Unexpected token "name" of value "entry" ("end of statement block" expected) in "emails/_workshop-status" at line 4.
```

**Comment by anthonyjc** [comment]
Hi @siebird -

Thanks.  Yes if you're using the `entries.onSaveEntry` event as your Blueprint trigger, you should be able to access the entry's fields from within your email template:

```
  <p>Status update for {{ entry.workshopName }}:</p>
```

Could you show me an example of the email template you're having trouble with?

**Comment by siebird** [comment]
@anthonyjc thanks for the quick response. Sorry for the delay–just getting back to this. 

The template is straight forward as I'm using the `entries.onSaveEntry` event as my trigger. 

```
{% extends 'layouts/_email' %}

{% set emailTitle = 'Workshop Status Update ' ~ siteName %}
{% set actionUrl =  entry.url ~ '/' entry.accessToken %}
{% set actionLabel = 'View Itinerary' %}
```

**Comment by anthonyjc** [comment]
No worries.  This might just be a missing tilde in your concatenation on line 4.  Can you try the below?

`
{% set actionUrl =  entry.url ~ '/' ~ entry.accessToken %}
`

**Comment by siebird** [comment]
Doh! Sorry for the troubles. Totally missed that
